name: Publish Commander to PyPi

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version to release (Tag from Keeper-Security/keeper-sdk-pyton)
        required: true

jobs:
  build-n-publish:
    name: Build and publish Keeper SDK for Python ðŸ“¦ to PyPI
    runs-on: ubuntu-latest
    timeout-minutes: 25     # To keep builds from running too long

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          architecture: 'x64'

      - name: Build the package
        run: |
          python -m pip install -U setuptools pip build wheel twine
          python -m build --wheel

      - name: Archive the package
        uses: actions/upload-artifact@v3
        with:
          name: KeeperSdkWheel
          retention-days: 1
          path: dist/*
          if-no-files-found: error

      - name: Publish Commander to test PyPi
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_TOKEN }}
        run: |
          twine upload  -r testpypi dist/*


  publish-pypi:
    name: Publish Keeper SDK to PyPi
    runs-on: ubuntu-latest
    needs: [build-n-publish]
    environment: prod

    steps:
      - uses: actions/download-artifact@v4.1.7
        with:
          name: CommanderWheel
          path: dist

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          architecture: 'x64'

      - name: Retrieve secrets from Keeper
        id: ksecrets
        uses: Keeper-Security/ksm-action@master
        with:
          keeper-secret-config: ${{ secrets.KSM_COMMANDER_SECRET_CONFIG }}
          secrets: |
            gD5LOOhI5QbnSFk8mIg3gg/field/password > PYPI_PASSWORD

      - name: Publish to PyPi
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ steps.ksecrets.outputs.PYPI_PASSWORD }}
        run: |
          python -m pip install -U setuptools pip wheel twine
          twine upload dist/*
